# Generated by Django 2.2 on 2020-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20200714_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
