# Generated by Django 2.2 on 2020-07-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20200715_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='date_remaining',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='prize',
            field=models.CharField(default=10, max_length=20),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='categories',
            field=models.ManyToManyField(related_name='challenges', to='challenge.Category'),
        ),
    ]
