# Generated by Django 2.2 on 2020-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20200716_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='date_pub',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date_remaining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
