# Generated by Django 2.2 on 2020-07-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_remove_answer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_slug', to='challenge.Challenge'),
        ),
    ]
