# Generated by Django 2.2 on 2020-07-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_answer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='slug',
        ),
    ]
