# Generated by Django 2.2 on 2020-07-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_answer_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='prize',
            field=models.IntegerField(default=10, max_length=20),
        ),
    ]
