# Generated by Django 2.2 on 2020-07-30 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0012_auto_20200729_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
    ]
