# Generated by Django 2.2 on 2020-08-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_challenge_challenge_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='challenge_author',
        ),
    ]
