# Generated by Django 2.2 on 2020-08-03 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0014_remove_challenge_challenge_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenge_img',
            field=models.ImageField(blank=True, upload_to='challenge_img'),
        ),
    ]
