# Generated by Django 2.2 on 2020-08-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0015_auto_20200803_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='voites',
            field=models.IntegerField(default=0),
        ),
    ]
