# Generated by Django 2.2 on 2020-08-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_answer_voites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='voites',
            new_name='answer_like',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_dislike',
            field=models.IntegerField(default=0),
        ),
    ]
