# Generated by Django 2.2 on 2020-08-12 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0017_auto_20200812_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_dislike',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_like',
        ),
        migrations.CreateModel(
            name='Answer_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='Like')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Answer_like', to='challenge.Answer', verbose_name='Ответ на челендж')),
                ('liked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Liked_by', to=settings.AUTH_USER_MODEL, verbose_name='Поставил лайк')),
            ],
        ),
    ]
