# Generated by Django 2.2 on 2020-08-12 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0018_auto_20200812_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer_like',
            name='liked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Liked_by', to=settings.AUTH_USER_MODEL, verbose_name='Поставил лайк'),
        ),
    ]
