# Generated by Django 2.2 on 2020-08-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0019_auto_20200812_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer_like',
        ),
    ]
