# Generated by Django 2.2 on 2020-08-14 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0020_delete_answer_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_dislike',
            field=models.ManyToManyField(blank=True, related_name='answer_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_like',
            field=models.ManyToManyField(blank=True, related_name='answer_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), (None, 'None')], default=None, max_length=7)),
                ('for_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
