# Generated by Django 2.2 on 2020-08-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0022_auto_20200819_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='challenge_img',
        ),
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='challenge/'),
        ),
    ]
