# Generated by Django 2.2 on 2020-08-23 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0025_auto_20200823_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_dislike',
            field=models.ManyToManyField(blank=True, related_name='answer_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_like',
            field=models.ManyToManyField(blank=True, related_name='answer_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
