# Generated by Django 2.2 on 2020-08-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0026_auto_20200823_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_dislike',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_like',
        ),
    ]
