# Generated by Django 2.2 on 2020-08-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0028_answerlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='answer_pk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='challenge.Answer'),
        ),
    ]
